name: movie

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  video_player: ^2.10.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  chewie: ^1.13.0
  video_player_win: ^3.2.0
  intl: ^0.20.2
  pull_to_refresh: ^2.0.0
  window_manager: ^0.5.1
  wakelock_plus: ^1.4.0
  app_links: ^6.4.1
  google_sign_in: ^7.2.0
  background_downloader: ^9.5.9
  path_provider: ^2.1.6
  qr_flutter: ^4.1.0
  crypto: ^3.0.7
  connectivity_plus: ^7.3.1
  package_info_plus: ^10.2.1
  volume_controller: ^3.7.1
  screen_brightness: ^2.1.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.7


flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_native_splash:
  color: "#171717"
  image: assets/icon/icon.png
  android_12:
    color: "#171717"
    image: assets/icon/icon.png
  fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFBADE"

